name: Deploy to Workshop

on:
  push:
    branches:
      - main

jobs:
  rimworld-deploy:
    uses: MemeGoddess/RimWorld-Deployment-Pipeline/.github/workflows/deploy.yml@beta
    secrets: inherit
    with:
      workshopId: '2009463077'
      ProjectFiles: 'Source/RealisticAxialTilt.csproj'
