name: Build and Commit on PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'Source/**'

permissions:
  contents: write

jobs:
  pr-closed-build:
    uses: MemeGoddess/RimWorld-Deployment-Pipeline/.github/workflows/pr-closed.yml@beta
    with:
      ProjectFiles: 'Source/RealisticAxialTilt.csproj'
